name: Build and Test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Match your project's Node.js version
        cache: 'yarn'

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Build Project
      run: yarn build

    # Add Linting Step (Optional but Recommended)
    # - name: Lint Code
    #   run: npm run lint # Assumes you have a lint script in package.json
    #   # Or: yarn lint

    # Add Testing Step (Optional but Recommended)
    # - name: Run Tests
    #   run: npm test # Assumes you have a test script in package.json
    #   # Or: yarn test
